ALTER TABLE "Dewanyah" ADD COLUMN "anchorLat" DOUBLE PRECISION;
ALTER TABLE "Dewanyah" ADD COLUMN "anchorLng" DOUBLE PRECISION;

ALTER TABLE "DewanyahRequest" ADD COLUMN "anchorLat" DOUBLE PRECISION;
ALTER TABLE "DewanyahRequest" ADD COLUMN "anchorLng" DOUBLE PRECISION;
